###batch-dev
server.port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: k10a401.p.ssafy.io:9092 # Kafka ???? ?? ?? ??? ??? ??? : ?? ??
      group-id: consumer_group01 # Group Id
      auto-offset-reset: latest # offset ? ??? ? ?? ?? ?? ??? ???? ?? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: com.fasterxml.jackson.databind.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: test

logging:
  level:
    org.hibernate.SQL: debug

#kafka:
#  consumer:
#    bootstrap-servers: localhost:9092 # Kafka ???? ?? ?? ??? ??? ??? : ?? ??
#    group-id: consumer_group01 # Group Id
#    auto-offset-reset: earliest # offset ? ??? ? ?? ?? ?? ??? ???? ?? ??