server:
  #  tomcat:
  #    accept-count: 500
  ##    max-keep-alive-requests: -1
  ##    max-connections: 30000 # default 8192
  ##    connection-timeout: # default 60000 ms
  #    threads:
  #      max: 200 # default 200 / thread 경합..? 주의
  #      min-spare: 200

  port: 8081

  tomcat:
    mbeanregistry:
      enabled: true
    uri-encoding: UTF-8

  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api-server

  data:
    mongodb:
      uri: mongodb://root:example@k10a401.p.ssafy.io:27017/qqueueing?authSource=admin&authMechanism=SCRAM-SHA-1
#      uri: mongodb://localhost:27017/qqueueing
      auto-index-creation: true  # 자동 인덱스


  threads:
    virtual:
      enabled: true
#      enabled: false

servers: # 타 서버들의 정보 기록
  consumer: k10a401.p.ssafy.io:8082
#  consumer: localhost:8082
  front: qqueueing-frontend:3000/waiting
  main: http://k10a401.p.ssafy.io # Nginx 거치도록 포트번호 제거

  replace-url: http://host.docker.internal # replace url value for forwarding to target

#  front: http://localhost:8081/waiting/testQueuePage

kafka:
  broker: k10a401.p.ssafy.io:9092
  topic-names:
    enter: test3

  partition:
    max-index: 20

# actuator
management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitoring"

  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: qqueueing
    company: 4EVERY1

#shell script 실행 관련
shell:
  path:
    C:/Users/SSAFY/Desktop/qqueueing/tmp
  fileNm: test.bat
